services:
  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
    - ./laravel-app:/var/www/html
    ports: 
    - 8001:8001

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-laravel
    ports:
    - 3307:3307
   
         
