services:
  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
    - ./data:/var/lib/mysql
    ports: 
    - 8001:8001
    depends_on:
      - mysql_db 

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-laravel
    ports:
    - 3306:3306
   
         
